version: '3.8'

services:
  web:
    image: php:8.2-apache
    container_name: uas_ppw_web
    ports:
      - "8080:80"
    volumes:
      -  ./:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: uas_ppw_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: uas_ppw_2
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: uas_ppw_pma
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root

volumes:
  db_data:
